DTC_INCLUDE += $(srctree)/../sm8450-modules/qcom/opensource/audio-kernel/include
KBUILD_DTC_INCLUDE += $(srctree)/../sm8450-modules/qcom/opensource/audio-kernel/include

# select based on the target
ifeq ($(CONFIG_MACH_SONY_PDX223),y)
SOMC_TARGET_PRODUCT := pdx223
endif
ifeq ($(CONFIG_MACH_SONY_PDX224),y)
SOMC_TARGET_PRODUCT := pdx224
endif

SOMC_TARGET_OPERATOR := generic
SOMC_PLATFORM := nagara

SOMC_PRODUCT_OPERATOR = $(SOMC_TARGET_PRODUCT)_$(SOMC_TARGET_OPERATOR)

ifeq ($(SOMC_PLATFORM), nagara)
ifeq ($(SOMC_PRODUCT_OPERATOR),pdx223_generic)
dtbo-$(CONFIG_ARCH_WAIPIO) += waipio-audio.dtbo \
                  somc-nagara-audio-pdx223.dtbo
else
dtbo-$(CONFIG_ARCH_WAIPIO) += waipio-audio.dtbo \
                  somc-nagara-audio-pdx223-crossflash.dtbo
endif

ifeq ($(SOMC_PRODUCT_OPERATOR),pdx224_generic)
dtbo-$(CONFIG_ARCH_WAIPIO) += waipio-audio.dtbo \
                  somc-nagara-audio-pdx224.dtbo
else
dtbo-$(CONFIG_ARCH_WAIPIO) += waipio-audio.dtbo \
                  somc-nagara-audio-pdx224-crossflash.dtbo
endif


else
dtbo-$(CONFIG_ARCH_WAIPIO) += waipio-audio.dtbo \
                 waipio-audio-cdp.dtbo \
                 waipio-audio-mtp.dtbo \
                 waipio-audio-qrd.dtbo \
                 waipio-audio-atp.dtbo \
                 waipio-audio-rumi.dtbo \
                 waipio-audio-hdk.dtbo

endif

 always-y    := $(dtb-y) $(dtbo-y)
 subdir-y    := $(dts-dirs)
 clean-files    := *.dtb *.dtbo
